name: "Test Pull Request"

on:
  pull_request:
    branches: [main]
  
  workflow_dispatch: 
    
env:
  PROJECT_PATH: "./src/Novu/Novu.csproj"
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: "https://api/nuget/org/v3/index.json"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      ## Restore Novu as a solution
      - name: Restore dependencies
        working-directory: ./src/
        run: dotnet restore

      ## Test Novu
      - name: Test
        working-directory: ./src
        
        ## this run should work but something is not picking up values and mapping in the configuration
        ## run: dotnet test -p:Novu__Url=https://api.novu.co/v1 -p:Novu__ApiKey=${{ secrets.NOVU_API_KEY }}
        ## instead inject using the ad hoc environment variable override
        ## see https://github.com/novuhq/novu-dotnet/blob/main/src/Novu.Extensions/ConfigurationExtensions.cs
        ##
        ## also up the logging because when something is wrong it is hard to diagnose
        ##
        run: dotnet test --verbosity normal
        env:
          NOVU_API_URL: https://api.novu.co/v1
          NOVU_API_KEY: ${{ secrets.NOVU_API_KEY }}