name: "Test Pull Request"

on:
  pull_request:
    branches: [main]

env:
  PROJECT_PATH: "./src/Novu/Novu.csproj"
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: "https://api/nuget/org/v3/index.json"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      ## Restore Novu
      - name: Restore dependencies
        working-directory: ./src/Novu
        run: dotnet restore

      ## Build Novu
      - name: Build Novu
        working-directory: ./src/Novu
        run: dotnet build --no-restore

        ## Restore Novu.Tests
      - name: Restore test dependencies
        working-directory: ./src/Novu.Tests
        run: dotnet restore

      ## Test Novu
      - name: Test
        working-directory: ./src/Novu.Tests
        run: dotnet test -p:Novu__Url=https://api.novu.co/v1 -p:Novu__ApiKey=${{ secrets.NOVU_API_KEY }}


## name: Test
#        working-directory: ./src/Novu.Tests
#        run: dotnet test  -p:Novu__Url=https://api.novu.co/v1 -p:Novu__ApiKey=${{ secrets.NOVU_API_KEY }}